services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=messaging_app_db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=user_password
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: .
    container_name: messaging_app
    depends_on:
      - db
    env_file:
      - .env
    # to restart on failure
    restart: on-failure

volumes:
  mysql-data:
